// constants.js
module.exports = {
    BATCH_SIZE: 1000,
    MAX_NUMBER_OF_CLUES: 25,
    MIN_NUMBER_OF_CLUES: 18,
    PERCENTAGE_NUMBER_OF_XL_CLUES: 10.2,
    PERCENTAGE_NUMBER_OF_L_CLUES: 24.49,
    PERCENTAGE_NUMBER_OF_M_CLUES: 20.41,
    PERCENTAGE_NUMBER_OF_S_CLUES: 44.9,
    CLUE_LENGTH_XL: "8-9",
    CLUE_LENGTH_L: "5-7",
    CLUE_LENGTH_M: "4",
    CLUE_LENGTH_S: "1-3",
  };
  